version: "3"
services:
  web_backend:
    env_file: 
      - ./app.env
    build: .
    command: dockerize -wait tcp://${DATABASE_HOST}:${DATABASE_PORT} -timeout 30s /bin/bash start.sh
    ports:
      - "80:8000"
