version: "3"
services:
  web_backend:
    env_file: 
      - ./app.env
    build: .
    volumes:
      - ./:/src
    ports:
      - "8000:8000"

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./:/src
    depends_on:
      - web_backend
